"use client";

import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppLanguage = "en" | "ta";

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string) => string;
};

const STORAGE_KEY = "saree_app_language";

const TA: Record<string, string> = {
  "Dashboard": "முகப்புப்",
  "Orders": "ஆர்டர்கள்",
  "Add Order": "புதிய ஆர்டர்",
  "Product Codes": "புராடக்ட் கோட்ஸ்",
  "Product codes": "புராடக்ட் கோட்ஸ்",
  "Reports": "ரிப்போர்ட்ஸ்",
  "Settings": "செட்டிங்ஸ்",
  "Language": "மொழி",
  "Home": "முகப்புப்",
  "Log out": "லாக் அவுட்",
  "Logout": "லாக் அவுட்",
  "Hello,": "ஹலோ,",
  "Hello": "ஹலோ",
  "Theme": "ஆப் நிறம்",
  "Dark": "டார்க்",
  "Light": "லைட்",
  "Save": "சேவ்",
  "Save & Apply": "சேமித்துச் செயல்படுத்து",
  "Reset to Default": "மீண்டும் பழைய நிலைக்கு மாற்ற",
  "Cancel": "ரத்து செய்",
  "Delete": "டெலீட்",
  "Edit": "எடிட்",
  "Edit Order": "ஆர்டர் திருத்தம்",
  "Update Order": "ஆர்டரை புதுப்பிக்கவும்",
  "Download": "டவுன்லோட்",
  "Upload": "அப்லோட்",
  "Generate": "ஜெனரேட்",
  "Share via WhatsApp": "வாட்ஸ்அப் வழியாகப் பகிர",
  "Sync Now": "இப்போதே புதுப்பிக்கவும்",
  "Back": "பின் செல்ல",
  "Close": "மூட",
  "Try again": "மீண்டும் முயற்சி செய்",
  "Loading": "லோடிங்",
  "Saved": "சேமிக்கப்பட்டது",
  "Failed": "ஃபெயில்டு",
  "Today": "இன்று",
  "Yesterday": "நேற்று",
  "This Week": "இந்த வாரம்",
  "Last Week": "கடந்த வாரம்",
  "This Month": "இந்த மாதம்",
  "Last Month": "கடந்த மாதம்",
  "Quarter": "காலாண்டு",
  "Year": "ஆண்டு",
  "Custom": "விருப்பப்படியே",
  "Custom Range": "விருப்பப்படியே",
  "From": "முதல்",
  "To": "வரை",
  "To Date": "எந்த தேதி வரை?",
  "Booking date": "புக்கிங் செய்த தேதி",
  "Dispatched date": "அனுப்பி வைக்கப்பட்ட தேதி",
  "All Orders": "அனைத்து ஆர்டர்கள்",
  "Move to Dispatch": "அனுப்புதலுக்கு மாற்றுக",
  "TO (Customer)": "பெறுநர் (வாடிக்கையாளர் பெயர்)",
  "FROM (Sender)": "அனுப்புநர்",
  "TO (customer address)": "பெறுநர் முகவரி (கஸ்டமர் முகவரி )",
  "FROM (our address)": "அனுப்புநர் முகவரி (நமது முகவரி)",
  "Product Details": "எண்ணிக்கை",
  "Qty": "எண்ணிக்கை",
  "Qty (optional)": "எண்ணிக்கை",
  "Booked By": "ஆர்டர் எடுத்தவர் (நமது)",
  "Booked mobile number": "ஆர்டர் எடுத்தவர் மொபைல்",
  "Booked Mobile No": "ஆர்டர் எடுத்தவர் மொபைல்",
  "Courier Name": "கூரியர்",
  "Tracking number": "டிராக்கிங் எண்",
  "Tracking / Consignment / LR Number": "டிராக்கிங் / கன்சைன்மென்ட் / LR எண்",
  "Tracking / Consignment / LR Number (optional)": "டிராக்கிங் / கன்சைன்மென்ட் / LR எண்",
  "Consignment number": "கன்சைன்மென்ட் எண்",
  "Recipient (To)": "பெறுநர்",
  "Order not found.": "ஆர்டர் கண்டறியப்படவில்லை",
  "Order not found": "ஆர்டர் கண்டறியப்படவில்லை",
  "Add New Order": "புதிய ஆர்டர்",
  "Recipient address and details": "பெறுநர் முகவரி மற்றும் விவரங்கள்",
  "Sender address and details": "அனுப்புநர் முகவரி மற்றும் விவரங்கள்",
  "Name": "பெயர்",
  "Mobile number": "அலைபேசி எண்",
  "Order saved": "ஆர்டர் சேமிக்கப்பட்டது",
  "Update failed": "புதுப்பிப்பு தோல்வி",
  "Save failed": "சேமிப்பு தோல்வி",
  "Saving…": "சேமிக்கப்படுகிறது…",
  "Search by mobile, name or consignment...": "மொபைல் எண், பெயர் அல்லது டிராக்கிங் எண் மூலம் தேடுக",
  "Filter orders": "ஆர்டர்களை வடிகட்டு",
  "Filter": "வடிகட்டி",
  "Clear dates": "தேதிகளை அழி",
  "Order details": "ஆர்டர் விவரங்கள்",
  "Pack these items": "பேக் செய்ய வேண்டிய பொருட்கள்",
  "Customer": "வாடிக்கையாளர்",
  "Loading items…": "பொருட்கள் ஏற்றப்படுகின்றன…",
  "No photo": "புகைப்படம் இல்லை",
  "No items listed for this order.": "இந்த ஆர்டருக்கு பொருட்கள் பட்டியலிடப்படவில்லை.",
  "Show Result": "முடிவை காட்டு",
  "Booking From date": "புக்கிங்: முதல்",
  "Booking To date": "புக்கிங்: வரை",
  "Dispatch From date": "அனுப்பி வைத்த தேதி முதல்",
  "Dispatch To date": "அனுப்பி வைத்த தேதி வரை",
  "Booking Details": "ஆர்டர் விவரங்கள்",
  "No orders found.": "ஆர்டர்கள் எதுவும் இல்லை.",
  "No matching orders.": "பொருந்தும் ஆர்டர்கள் இல்லை.",
  "Dispatch": "அனுப்பு",
  "Dispatching…": "அனுப்பப்படுகிறது…",
  "Move to Pending": "நிலுவைக்கு மாற்று",
  "Print": "பிரிண்ட்",
  "Printing…": "பிரிண்ட் ஆகிறது…",
  "If download didn't start, tap here and long‑press to save.": "டவுன்லோட் துவங்கவில்லை என்றால், இங்கே தட்டி நீண்ட நேரம் அழுத்தி சேமிக்கவும்.",
  "Account": "கணக்கு",
  "Syncing...": "புதுப்பிக்கப்படுகிறது...",
  "Not synced yet": "இன்னும் புதுப்பிக்கப்படவில்லை",
  "Product Code Settings": "புராடக்ட் கோட் செட்டிங்ஸ்",
  "Preview": "முன்னோட்டம்",
  "Text Placement": "உரை இடம்",
  "Text Color": "உரை நிறம்",
  "Saved!": "சேமிக்கப்பட்டது!",
  "Sales Reports": "விற்பனை அறிக்கைகள்",
  "Select Report Period": "அறிக்கை காலத்தைத் தேர்ந்தெடுக்கவும்",
  "From Date": "முதல் தேதி",
  "Dispatched Orders": "அனுப்பப்பட்ட ஆர்டர்கள்",
  "Total Sarees (from qty)": "மொத்த சேலைகள் (அளவிலிருந்து)",
  "Sales increased": "விற்பனை உயர்ந்தது",
  "Sales decreased": "விற்பனை குறைந்தது",
  "Download PDF Report (Auditor / IT Filing)": "PDF அறிக்கையை பதிவிறக்கு (ஆடிட்டர் / IT Filing)",
  "PDF includes summary, comparison with previous period, and detailed order table. Suitable for auditors and tax filing.": "PDF-ல் சுருக்கம், முந்தைய கால ஒப்பீடு, மற்றும் விரிவான ஆர்டர் அட்டவணை இருக்கும். ஆடிட்டர் மற்றும் வரி தாக்கலுக்கு பொருத்தமானது.",
  "Dispatched orders only, by dispatch date. View analytics and download PDF for auditors or IT filing.": "அனுப்பப்பட்ட ஆர்டர்கள் மட்டும், அனுப்பிய தேதிப்படி. பகுப்பாய்வு பார்க்கவும் மற்றும் ஆடிட்டர்/IT தாக்கலுக்காக PDF பதிவிறக்கவும்.",
  "Non-image files were skipped.": "படம் அல்லாத கோப்புகள் தவிர்க்கப்பட்டன",
  "Delete this batch?": "இந்த பேட்சை நீக்கவா?",
  "No saved images for this batch.": "இந்த பேட்சிற்கு சேமித்த படங்கள் இல்லை.",
  "Could not save images.": "படங்களை சேமிக்க முடியவில்லை.",
  "No batches in this period. Try another date range.": "இந்த காலப்பகுதியில் பேட்ச்கள் இல்லை. வேறு தேதியை முயற்சிக்கவும்.",
  "No photos selected": "புகைப்படங்கள் எதுவும் தேர்ந்தெடுக்கப்படவில்லை",
  "photo selected": "புகைப்படங்கள் தேர்ந்தெடுக்கப்பட்டது",
  "Pending": "நிலுவை",
  "Dispatched": "அனுப்பப்பட்டது",
  "Total Orders": "மொத்த ஆர்டர்கள்",
  "Own": "நமது",
  "No change from the previous period.": "பழைய காலத்தில் இருந்து எந்த மாற்றமும் இல்லை",
  "Failed to load data": "டேட்டா லோட் ஆகவில்லை",
  "Admin": "அட்மின்",
  "Workers": "பணியாளர்",
  "No workers yet.": "பணியாளர் யாரும் இல்லை",
  "No workers yet": "பணியாளர் யாரும் இல்லை",
  "PDF Settings": "PDF செட்டிங்ஸ்",
  "Printer Setup": "பிரிண்டர் செட்டப்",
  "API Settings": "API செட்டிங்ஸ்",
  "Velo API Key": "Velo API கீ",
  "API Base URL": "API Base URL",
  "Test Connection": "இணைப்பை சோதிக்கவும்",
  "Testing…": "சோதிக்கப்படுகிறது…",
  "Connection successful.": "இணைப்பு வெற்றி.",
  "Connection failed.": "இணைப்பு தோல்வி.",
  "Sync Website Orders": "வெப்சைட் ஆர்டர்களை புதுப்பிக்கவும்",
  "No new website orders.": "புதிய வெப்சைட் ஆர்டர்கள் இல்லை.",
  "Imported {count} website order(s).": "{count} வெப்சைட் ஆர்டர்(கள்) இறக்குமதி செய்யப்பட்டது.",
  "No new orders. {count} already imported.": "புதிய ஆர்டர்கள் இல்லை. {count} ஏற்கனவே இறக்குமதி செய்யப்பட்டது.",
  "Enable automatic sync": "தானியங்கி புதுப்பிப்பை இயக்கு",
  "Saved Connections": "சேமித்த இணைப்புகள்",
  "No API connections yet.": "API இணைப்புகள் இன்னும் இல்லை.",
  "Edit API Connection": "API இணைப்பை திருத்து",
  "Add API Connection": "API இணைப்பை சேர்",
  "API key is required.": "API கீ தேவை.",
  "Could not save API settings.": "API செட்டிங்ஸ் சேமிக்க முடியவில்லை.",
  "API settings saved.": "API செட்டிங்ஸ் சேமிக்கப்பட்டது.",
  "Delete this API connection?": "இந்த API இணைப்பை நீக்கவா?",
  "Could not delete API connection.": "API இணைப்பை நீக்க முடியவில்லை.",
  "API connection removed.": "API இணைப்பு நீக்கப்பட்டது.",
  "Last synced": "கடைசி புதுப்பிப்பு",
  "Enabled": "இயக்கப்பட்டது",
  "Disabled": "நிறுத்தப்பட்டது",
  "Show": "காட்டு",
  "Hide": "மறை",
  "Label": "லேபிள்",
  "Web": "வெப்",
  "Paid": "பேடு",
  "Unpaid": "பேட் இல்லை",
  "Updated {count} order payment status.": "{count} ஆர்டர் பேமெண்ட் நிலை புதுப்பிக்கப்பட்டது.",
  "Connect your Velo website to import orders automatically every 15 seconds while the app is open.": "ஆப் திறந்திருக்கும் போது ஒவ்வொரு 15 வினாடிக்கும் வெப்சைட் ஆர்டர்களை தானாக இறக்குமதி செய்ய Velo வெப்சைட்டை இணைக்கவும்.",
  "Duplicate orders are skipped using the website order ID.": "வெப்சைட் ஆர்டர் ID மூலம் நகல் ஆர்டர்கள் தவிர்க்கப்படும்.",
  "Content Type": "கன்டென்ட் டைப்",
  "Text size": "டெக்ஸ்ட் சைஸ்",
  "Logo Zoom": "லோகோ ஜூம்",
  "Y Position": "Y பொசிஷன்",
  "Live Preview": "லைவ் பிரிவியூ",
  "Sample Image": "சாம்பிள் இமேஜ்",
  "Manual Add (fallback)": "மேனுவல் ஆட் (ஃபால்பேக்)",
  "Top Right": "மேல் வலது",
  "Top Left": "மேல் இடது",
  "Bottom Left": "கீழ் இடது",
  "Bottom Right": "கீழ் வலது",
  "Red": "சிவப்பு",
  "White": "வெள்ளை",
  "Black": "கருப்பு",
  "Green": "பச்சை",
  "Blue": "நீலம்",
  "Yellow": "மஞ்சள்",
  "Default": "இயல்புநிலை",
  "Login": "லாகின்",
  "REGISTER": "பதிவு செய்",
  "Create your account": "உங்கள் கணக்கை உருவாக்கவும்",
  "Password reset successfully. Sign in with your new password.": "கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது. புதிய கடவுச்சொல்லால் உள்நுழைக.",
  "This account is already signed in on the maximum number of devices.": "இந்த கணக்கு ஏற்கனவே அதிகபட்ச சாதனங்களில் உள்நுழைந்துள்ளது.",
  "Need another device? Contact us on WhatsApp.": "மற்றொரு சாதனம் வேண்டுமா? வாட்ஸ்அப் மூலம் எங்களை தொடர்பு கொள்ளவும்.",
  "Email": "மின்னஞ்சல்",
  "Password": "கடவுச்சொல்",
  "Forgot Password?": "கடவுச்சொல் மறந்துவிட்டதா?",
  "Signing in…": "உள்நுழைகிறது…",
  "Continue with Google": "Google மூலம் தொடரவும்",
  "Signing in with Google…": "Google மூலம் உள்நுழைகிறது…",
  "Google sign-in failed.": "Google உள்நுழைவு தோல்வியடைந்தது.",
  "Google sign-in failed. Please try again.": "Google உள்நுழைவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.",
  "Please add your mobile number before continuing with Google.": "Google உள்நுழைவுக்கு முன் உங்கள் மொபைல் எண்ணை சேர்க்கவும்.",
  "Enter a valid mobile number (at least 10 digits).": "சரியான மொபைல் எண்ணை உள்ளிடவும் (குறைந்தது 10 இலக்கங்கள்).",
  "required for Google sign-in": "Google உள்நுழைவுக்கு அவசியம்",
  "Add your mobile number before using Google sign-in.": "Google உள்நுழைவைப் பயன்படுத்தும் முன் மொபைல் எண்ணை சேர்க்கவும்.",
  "Mobile number is required for Google sign-in.": "Google உள்நுழைவுக்கு மொபைல் எண் அவசியம்.",
  "Add your mobile number below, then try Google sign-in again.": "கீழே மொபைல் எண்ணை சேர்த்து, மீண்டும் Google உள்நுழைவை முயற்சிக்கவும்.",
  "Completing sign-in…": "உள்நுழைவு முடிக்கப்படுகிறது…",
  "or": "அல்லது",
  "or sign in with email": "அல்லது மின்னஞ்சல் மூலம் உள்நுழையவும்",
  "or sign up with email": "அல்லது மின்னஞ்சல் மூலம் பதிவு செய்யவும்",
  "Login with email": "மின்னஞ்சல் மூலம் உள்நுழை",
  "Register with email": "மின்னஞ்சல் மூலம் பதிவு செய்",
  "Add your mobile number": "உங்கள் மொபைல் எண்ணை சேர்க்கவும்",
  "Required to complete signup. You can continue once your number is saved.": "பதிவை முடிக்க மொபைல் எண் அவசியம். சேமித்த பிறகு தொடரலாம்.",
  "Required for email signup.": "மின்னஞ்சல் பதிவுக்கு அவசியம்.",
  "No account found for this email. Please register.": "இந்த மின்னஞ்சலுக்கு கணக்கு இல்லை. பதிவு செய்யவும்.",
  "Don't have an account?": "கணக்கு இல்லையா?",
  "Register": "பதிவு செய்",
  "Already have an account?": "ஏற்கனவே கணக்கு உள்ளதா?",
  "Mobile Number": "அலைபேசி எண்",
  "Creating account…": "கணக்கு உருவாக்கப்படுகிறது…",
  "Open Gmail": "Gmail திறக்கவும்",
  "This email is already registered.": "இந்த மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.",
  "Forgot password": "கடவுச்சொல் மறந்துவிட்டதா",
  "Forgot Password": "கடவுச்சொல் மறந்துவிட்டதா",
  "Failed to send reset email": "ரீசெட் மின்னஞ்சலை அனுப்ப முடியவில்லை",
  "Enter your email to receive a reset link.": "ரீசெட் லிங்க் பெற உங்கள் மின்னஞ்சலை உள்ளிடவும்.",
  "Check your email for the reset link.": "ரீசெட் லிங்கிற்காக உங்கள் மின்னஞ்சலை சரிபார்க்கவும்.",
  "Sending…": "அனுப்பப்படுகிறது…",
  "Send Reset Link": "ரீசெட் லிங்க் அனுப்பு",
  "Back to Login": "லாகினுக்கு திரும்பு",
  "Invalid or expired reset link. Request a new one.": "ரீசெட் லிங்க் தவறானது அல்லது காலாவதியானது. புதியதை கோரவும்.",
  "Password updated. Redirecting to login…": "கடவுச்சொல் புதுப்பிக்கப்பட்டது. லாகினுக்கு மாற்றப்படுகிறது…",
  "Set new password": "புதிய கடவுச்சொல் அமைக்கவும்",
  "Set New Password": "புதிய கடவுச்சொல் அமைக்கவும்",
  "Enter your new password below.": "புதிய கடவுச்சொல்லை கீழே உள்ளிடவும்.",
  "New password": "புதிய கடவுச்சொல்",
  "Confirm password": "கடவுச்சொல்லை உறுதிப்படுத்து",
  "At least 6 characters": "குறைந்தது 6 எழுத்துகள்",
  "Confirm new password": "புதிய கடவுச்சொல்லை உறுதிப்படுத்து",
  "Update password": "கடவுச்சொல்லை புதுப்பி",
  "Reset Password": "கடவுச்சொல் மீட்டமை",
  "Password must be at least 6 characters.": "கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.",
  "Passwords do not match.": "கடவுச்சொற்கள் பொருந்தவில்லை.",
  "Failed to update password. The link may have expired.": "கடவுச்சொல்லை புதுப்பிக்க முடியவில்லை. லிங்க் காலாவதியாகி இருக்கலாம்.",
  "Password Changed!": "கடவுச்சொல் மாற்றப்பட்டது!",
  "Your password has been updated. Sign in with your new password.": "உங்கள் கடவுச்சொல் புதுப்பிக்கப்பட்டது. புதிய கடவுச்சொல்லால் உள்நுழைக.",
  "Open App": "ஆப்பை திறக்கவும்",
  "Show password": "கடவுச்சொல்லை காட்டு",
  "Hide password": "கடவுச்சொல்லை மறை",
  "Refer a Friend": "நண்பருக்குப் பகிர",
  "Join WhatsApp": "வாட்ஸ்அப்பில் இணைய",
  "Admin email": "அட்மின் இமெயில்",
  "Worker email": "பணியாளர் இமெயில்",
  "Enter an email.": "மின்னஞ்சலை உள்ளிடவும்.",
  "Use a different email than your admin account.": "அட்மின் கணக்கை விட வேறு மின்னஞ்சலை பயன்படுத்தவும்.",
  "This email is already assigned as a worker.": "இந்த மின்னஞ்சல் ஏற்கனவே வேலைக்காரருக்கு ஒதுக்கப்பட்டுள்ளது.",
  "Adding…": "சேர்க்கப்படுகிறது…",
  "Add worker": "பணியாளரைச் சேர்",
  "Remove": "நீக்கு",
  "Generating": "உருவாக்கப்படுகிறது",
  "Review": "மதிப்பாய்வு",
  "Error": "பிழை",
  "Generating product codes…": "புராடக்ட் கோடுகள் உருவாக்கப்படுகிறது…",
  "Decrease quantity": "அளவை குறை",
  "Increase quantity": "அளவை கூட்டு",
  "Save batch?": "பேட்சை சேமிக்கவா?",
  "You have not saved this batch. Save before leaving, or discard and go back.": "இந்த பேட்ச் இன்னும் சேமிக்கப்படவில்லை. வெளியேறும் முன் சேமிக்கவும் அல்லது நீக்கி திரும்பவும்.",
  "Discard": "நிராகரி",
  "Batch": "பேட்ச்",
  "No saved images for this batch (older batches may not have stored photos).": "இந்த பேட்சில் சேமித்த படங்கள் இல்லை (பழைய பேட்ச்களில் படங்கள் சேமிக்கப்படாமல் இருக்கலாம்).",
  "Verification Successful": "சரிபார்ப்பு வெற்றி",
  "Your email is verified. You can now sign in to your account.": "உங்கள் மின்னஞ்சல் சரிபார்க்கப்பட்டது. இப்போது உங்கள் கணக்கில் உள்நுழையலாம்.",
  "Continue in browser": "பிரௌசரில் தொடரவும்",
  "Verified": "சரிபார்க்கப்பட்டது",
  "Your email has been verified. You can now sign in to the app.": "உங்கள் மின்னஞ்சல் சரிபார்க்கப்பட்டது. இப்போது ஆப்பில் உள்நுழையலாம்.",
  "Or continue in browser": "அல்லது பிரௌசரில் தொடரவும்",
  "Supabase Connection Check": "Supabase இணைப்பு சோதனை",
  "Checking...": "சோதிக்கிறது...",
  "Project URL:": "ப்ராஜெக்ட் URL:",
  "(not set)": "(அமைக்கப்படவில்லை)",
  "Auth:": "ஆத்:",
  "DB:": "டிபி:",
  "Make sure this URL matches your Supabase project. Go to supabase.com → your project → Project Settings → API to verify.": "இந்த URL உங்கள் Supabase ப்ராஜெக்டுடன் பொருந்துகிறதா உறுதிப்படுத்தவும். supabase.com → உங்கள் ப்ராஜெக்ட் → Project Settings → API சென்று சரிபார்க்கவும்.",
  "PDF Download Test Page": "PDF டவுன்லோட் சோதனை பக்கம்",
  "Test Actions": "சோதனை செயல்கள்",
  "Test Single Order PDF": "ஒற்றை ஆர்டர் PDF சோதனை",
  "Test Multiple Orders PDF": "பல ஆர்டர் PDF சோதனை",
  "Test Blob Creation": "Blob உருவாக்கம் சோதனை",
  "Clear Logs": "லாக்களை நீக்கு",
  "Debug Logs": "டீபக் லாக்கள்",
  "No logs yet. Click a test button above.": "இன்னும் லாக்கள் இல்லை. மேலே உள்ள சோதனை பொத்தானை அழுத்தவும்.",
  "How to Use": "எப்படி பயன்படுத்துவது",
  "Download PDF": "PDF பதிவிறக்கு",
  "Print Labels": "லேபிள் பிரிண்ட்",
  "Save Changes": "மாற்றங்களை சேமி",
  "Reset to defaults": "இயல்புநிலைக்கு மாற்று",
  "Upload Logo": "லோகோ அப்லோடு",
  "Enter Text": "உரை உள்ளிடவும்",
  "Choose file": "கோப்பு தேர்வு",
  "Change logo": "லோகோ மாற்று",
  "Uploading...": "அப்லோடு செய்கிறது...",
  "Formalize address": "முகவரியை ஒழுங்குபடுத்து",
  "Live preview below reflects these settings and PDF generation.": "கீழே உள்ள முன்னோட்டம் இந்த செட்டிங்ஸ் மற்றும் PDF உருவாக்கத்தை காட்டும்.",
  Products: "புராடக்ட்ஸ்",
  "Product List": "புராடக்ட் பட்டியல்",
  "Add Single Product": "ஒரு புராடக்ட் சேர்",
  "Add Bulk Products": "பல புராடக்ட் சேர்",
  "Sync Logs": "சின்க் லாக்கள்",
  "Product sync activity": "புராடக்ட் சின்க் செயல்பாடு",
  "Recent product API calls on this device. For troubleshooting uploads only.":
    "இந்த சாதனத்தில் சமீபத்திய புராடக்ட் API அழைப்புகள். அப்லோடு சிக்கல்களுக்கு மட்டும்.",
  "Show successful calls": "வெற்றிகரமான அழைப்புகளைக் காட்டு",
  "No failed product syncs.": "தோல்வியடைந்த புராடக்ட் சின்க் இல்லை.",
  "Website order alerts": "வலைத்தள ஆர்டர் எச்சரிக்கைகள்",
  "Sound and notification when a new customer order syncs from your website.":
    "வலைத்தளத்திலிருந்து புதிய ஆர்டர் வரும்போது ஒலி மற்றும் அறிவிப்பு.",
  "Enable order alerts": "ஆர்டர் எச்சரிக்கைகளை இயக்கு",
  "Test alert sound": "எச்சரிக்கை ஒலியை சோதி",
  'Enable "Show successful calls" to see recent activity.':
    "சமீபத்திய செயல்பாட்டைக் காண \"வெற்றிகரமான அழைப்புகளைக் காட்டு\" ஐ இயக்கவும்.",
  "Manage website products using your Velo API key.": "Velo API விசை மூலம் வலைத்தள புராடக்ட்களை நிர்வகிக்கவும்.",
  "Name or product code": "பெயர் அல்லது புராடக்ட் கோடு",
  "No products found.": "புராடக்ட்கள் இல்லை.",
  "No collection": "கலெக்ஷன் இல்லை",
  Stock: "ஸ்டாக்",
  Published: "வெளியிடப்பட்டது",
  "Load more": "மேலும் ஏற்று",
  "Loading more products…": "மேலும் புராடக்ட்கள் ஏற்றப்படுகிறது…",
  "Could not load more products.": "மேலும் புராடக்ட்களை ஏற்ற முடியவில்லை.",
  "Scroll down for more products": "மேலும் புராடக்ட்களுக்கு கீழே ஸ்க்ரோல் செய்யவும்",
  "All products loaded": "அனைத்து புராடக்ட்களும் ஏற்றப்பட்டன",
  "Searching…": "தேடுகிறது…",
  "Delete product \"{name}\"?": "புராடக்ட் \"{name}\" நீக்கவா?",
  "Product deleted.": "புராடக்ட் நீக்கப்பட்டது.",
  "Product code": "புராடக்ட் கோடு",
  "Website assigns the next ST product code automatically (same as shop admin).":
    "வலைத்தளம் அடுத்த ST புராடக்ட் கோடை தானாக வழங்கும் (கடை அட்மின் போல).",
  "Each image gets the next website ST code in order (shared with shop admin).":
    "ஒவ்வொரு படத்திற்கும் அடுத்த ST கோடு வரிசையாக கிடைக்கும் (கடை அட்மினுடன் பகிர்ந்து).",
  "Product created: {code}.": "புராடக்ட் உருவாக்கப்பட்டது: {code}.",
  "Product updated: {code}.": "புராடக்ட் புதுப்பிக்கப்பட்டது: {code}.",
  Description: "விளக்கம்",
  Collection: "கலெக்ஷன்",
  "Select collection": "கலெக்ஷன் தேர்வு",
  Badge: "பேட்ஜ்",
  None: "இல்லை",
  "New product": "புதிய புராடக்ட்",
  "Best sale": "சிறந்த விற்பனை",
  Featured: "சிறப்பு",
  Rating: "ரேட்டிங்",
  Price: "விலை",
  "Save as draft": "டிராஃப்டாக சேமி",
  "Draft product (hidden on website)": "டிராஃப்ட் புராடக்ட் (வலைத்தளத்தில் மறைக்கப்பட்டது)",
  Tags: "டேக்ஸ்",
  "Add tag and press Enter": "டேக் சேர்த்து Enter அழுத்தவும்",
  "Product image": "புராடக்ட் படம்",
  "Choose image": "படம் தேர்வு",
  "Enable size options": "சைஸ் விருப்பங்களை இயக்கு",
  Size: "சைஸ்",
  "Add size row": "சைஸ் வரி சேர்",
  "Please fix the highlighted fields.": "சிவப்பாக குறிக்கப்பட்ட புலங்களை சரிசெய்யவும்.",
  "Product saved successfully.": "புராடக்ட் வெற்றிகரமாக சேமிக்கப்பட்டது.",
  "Update product": "புராடக்ட் புதுப்பி",
  "Create product": "புராடக்ட் உருவாக்கு",
  "Preparing images": "படங்கள் தயாராகிறது",
  "Preparing image…": "படம் தயாராகிறது…",
  "Uploading product…": "புராடக்ட் அப்லோடு செய்கிறது…",
  "Please wait…": "தயவுசெய்து காத்திருக்கவும்…",
  "Publish on website": "வலைத்தளத்தில் வெளியிடு",
  "This product is saved as draft and hidden on the website.":
    "இந்த புராடக்ட் டிராஃப்டாக சேமிக்கப்பட்டு வலைத்தளத்தில் மறைக்கப்பட்டுள்ளது.",
  "This product will be visible on the website.":
    "இந்த புராடக்ட் வலைத்தளத்தில் தெரியும்.",
  "Updating…": "புதுப்பிக்கிறது…",
  "Uploading batch {current}/{total}": "பேட்ச் {current}/{total} அப்லோடு",
  "Uploading product {current}/{total}": "புராடக்ட் {current}/{total} அப்லோடு",
  "Creating products": "புராடக்ட்கள் உருவாகிறது",
  "Creating products…": "புராடக்ட்கள் உருவாகிறது…",
  " {count} warning(s).": " {count} எச்சரிக்கை(கள்).",
  "Created {count} product(s).": "{count} புராடக்ட்(கள்) உருவாக்கப்பட்டது.",
  "Name prefix": "பெயர் முன்னொட்டு",
  "e.g. Soft Silk Saree": "எ.கா. மென்மையான பட்டு சேலை",
  Images: "படங்கள்",
  "Select images from device": "சாதனத்திலிருந்து படங்கள் தேர்வு",
  "Create bulk products": "பல புராடக்ட் உருவாக்கு",
  "Generate batch": "பேட்ச் உருவாக்கு",
  "Saved batches": "சேமித்த பேட்ச்கள்",
  "Review batch": "பேட்ச் மதிப்பாய்வு",
  "Save batch": "பேட்ச் சேமி",
  "Stamp product codes on photos, save locally, share with description, then upload WebP to website.": "படங்களில் புராடக்ட் கோட் அச்சிட்டு, உள்ளே சேமித்து, விளக்கத்துடன் பகிர்ந்து, பிறகு WebP ஆக வலைத்தளத்தில் அப்லோடு செய்யவும்.",
  "Ready to upload": "அப்லோடுக்கு தயார்",
  "Partial upload": "பகுதி அப்லோடு",
  "Upload failed": "அப்லோடு தோல்வி",
  "Retry upload": "மீண்டும் அப்லோடு",
  "Waiting to prepare": "தயாரிக்க காத்திருக்கிறது",
  "Prep failed": "தயாரிப்பு தோல்வி",
  "Preparing upload": "அப்லோடுக்கு தயாராகிறது",
  "Upload complete": "அப்லோடு முடிந்தது",
  "Uploaded {count} product(s) to website.": "வலைத்தளத்தில் {count} புராடக்ட்(கள்) அப்லோடு செய்யப்பட்டது.",
  "Saved {count} image(s) to VeloBulkProducts.": "VeloBulkProducts இல் {count} படம்(கள்) சேமிக்கப்பட்டது.",
  "Could not share.": "பகிர முடியவில்லை.",
  "Share text copied. Paste into WhatsApp.": "பகிர்வு உரை நகலெடுக்கப்பட்டது. WhatsApp-ல் ஒட்டவும்.",
  "This batch was already downloaded. Download again?": "இந்த பேட்ச் ஏற்கனவே பதிவிறக்கப்பட்டது. மீண்டும் பதிவிறக்கவா?",
  "Bulk products": "பல புராடக்ட்கள்",
  "Bulk batches": "பல பேட்ச்கள்",
  "Create a batch here. Saved batches appear in Product List.": "இங்கே பேட்ச் உருவாக்கவும். சேமித்த பேட்ச்கள் புராடக்ட் பட்டியலில் தோன்றும்.",
  "Share stamped images": "முத்திரையிட்ட படங்களைப் பகிர்",
  "Share shop link": "கடை இணைப்பைப் பகிர்",
  "Publish the product before sharing shop link.": "கடை இணைப்பைப் பகிர்வதற்கு முன் புராடக்டை வெளியிடவும்.",
  "Order cart": "ஆர்டர் கார்ட்",
  "Add to order cart": "ஆர்டர் கார்ட்டில் சேர்",
  "Added to order cart. Set quantity below and share on WhatsApp.": "ஆர்டர் கார்ட்டில் சேர்க்கப்பட்டது. அளவை அமைத்து WhatsApp-ல் பகிரவும்.",
  "Publish the product before adding to order cart.": "ஆர்டர் கார்ட்டில் சேர்ப்பதற்கு முன் புராடக்டை வெளியிடவும்.",
  "Order cart is full. Share or clear it first.": "ஆர்டர் கார்ட் நிரம்பியது. முதலில் பகிரவும் அல்லது நீக்கவும்.",
  "Share cart on WhatsApp": "WhatsApp-ல் கார்ட்டைப் பகிர்",
  "Share on WhatsApp": "WhatsApp-ல் பகிர்",
  "Clear cart": "கார்ட்டை நீக்கு",
  "Your order:": "உங்கள் ஆர்டர்:",
  "Courier charges are included in the final price shown at checkout.": "செக்அவுட்டில் காட்டப்படும் இறுதி விலையில் கூரியர் கட்டணம் சேர்க்கப்பட்டுள்ளது.",
  "Open cart:": "கார்டைத் திற:",
  "qty total": "மொத்த அளவு",
  "Working…": "செயல்படுகிறது…",
  "Clear logs": "லாக்கள் நீக்கு",
  "Sync logs cleared.": "சின்க் லாக்கள் நீக்கப்பட்டது.",
  "No sync logs yet.": "இன்னும் சின்க் லாக்கள் இல்லை.",
  OK: "சரி",
};

const LanguageContext = createContext<LanguageContextValue>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>("en");

  useEffect(() => {
    if (typeof window === "undefined") return;
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved === "en" || saved === "ta") {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, lang);
    }
  };

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (key: string) => (language === "ta" ? (TA[key] ?? key) : key),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  return useContext(LanguageContext);
}

