"use client";

import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppLanguage = "en" | "ta";

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string) => string;
};

const STORAGE_KEY = "saree_app_language";

const TA: Record<string, string> = {
  "Dashboard": "முகப்புப்",
  "Orders": "ஆர்டர்கள்",
  "Add Order": "புதிய ஆர்டர்",
  "Product Codes": "புராடக்ட் கோட்ஸ்",
  "Product codes": "புராடக்ட் கோட்ஸ்",
  "Reports": "ரிப்போர்ட்ஸ்",
  "Settings": "செட்டிங்ஸ்",
  "Language": "மொழி",
  "Home": "முகப்புப்",
  "Log out": "லாக் அவுட்",
  "Logout": "லாக் அவுட்",
  "Hello,": "ஹலோ,",
  "Hello": "ஹலோ",
  "Theme": "தீம்",
  "Dark": "டார்க்",
  "Light": "லைட்",
  "Save": "சேவ்",
  "Save & Apply": "சேமித்துச் செயல்படுத்து",
  "Reset to Default": "மீண்டும் பழைய நிலைக்கு மாற்ற",
  "Cancel": "ரத்து செய்",
  "Delete": "டெலீட்",
  "Edit": "எடிட்",
  "Edit Order": "ஆர்டர் திருத்தம்",
  "Update Order": "ஆர்டரை புதுப்பிக்கவும்",
  "Download": "டவுன்லோட்",
  "Upload": "அப்லோட்",
  "Generate": "ஜெனரேட்",
  "Share via WhatsApp": "வாட்ஸ்அப் வழியாகப் பகிர",
  "Sync Now": "இப்போதே புதுப்பிக்கவும்",
  "Back": "பின் செல்ல",
  "Close": "மூட",
  "Try again": "மீண்டும் முயற்சி செய்",
  "Loading": "லோடிங்",
  "Saved": "சேமிக்கப்பட்டது",
  "Failed": "ஃபெயில்டு",
  "Today": "இன்று",
  "Yesterday": "நேற்று",
  "This Week": "இந்த வாரம்",
  "Last Week": "கடந்த வாரம்",
  "This Month": "இந்த மாதம்",
  "Last Month": "கடந்த மாதம்",
  "Quarter": "காலாண்டு",
  "Year": "ஆண்டு",
  "Custom": "விருப்பப்படியே",
  "Custom Range": "விருப்பப்படியே",
  "From": "முதல்",
  "To": "வரை",
  "To Date": "எந்த தேதி வரை?",
  "Booking date": "பதிவு செய்த தேதி",
  "Dispatched date": "அனுப்பி வைக்கப்பட்ட தேதி",
  "All Orders": "அனைத்து ஆர்டர்கள்",
  "Move to Dispatch": "அனுப்புதலுக்கு மாற்றுக",
  "TO (Customer)": "பெறுநர் (வாடிக்கையாளர்)",
  "FROM (Sender)": "அனுப்புநர்",
  "TO (customer address)": "பெறுநர் முகவரி",
  "FROM (our address)": "அனுப்புநர் முகவரி (நமது முகவரி)",
  "Product Details": "தயாரிப்பு விவரங்கள்",
  "Qty": "எத்தனை",
  "Qty (optional)": "எத்தனை",
  "Booked By": "பதிவு செய்தவர் (நமது)",
  "Booked mobile number": "பதிவு செய்தவரின் அலைபேசி எண் (நமது)",
  "Booked Mobile No": "பதிவு அலைபேசி எண் (நமது)",
  "Courier Name": "கூரியர்",
  "Tracking number": "டிராக்கிங் எண்",
  "Tracking / Consignment / LR Number": "டிராக்கிங் / கன்சைன்மென்ட் / LR எண்",
  "Tracking / Consignment / LR Number (optional)": "டிராக்கிங் / கன்சைன்மென்ட் / LR எண்",
  "Consignment number": "கன்சைன்மென்ட் எண்",
  "Recipient (To)": "பெறுநர்",
  "Order not found.": "ஆர்டர் கண்டறியப்படவில்லை",
  "Order not found": "ஆர்டர் கண்டறியப்படவில்லை",
  "Add New Order": "புதிய ஆர்டர்",
  "Recipient address and details": "பெறுநர் முகவரி மற்றும் விவரங்கள்",
  "Sender address and details": "அனுப்புநர் முகவரி மற்றும் விவரங்கள்",
  "Name": "பெயர்",
  "Mobile number": "அலைபேசி எண்",
  "Order saved": "ஆர்டர் சேமிக்கப்பட்டது",
  "Update failed": "புதுப்பிப்பு தோல்வி",
  "Save failed": "சேமிப்பு தோல்வி",
  "Saving…": "சேமிக்கப்படுகிறது…",
  "Search by mobile, name or consignment...": "மொபைல், பெயர் அல்லது கன்சைன்மென்ட் மூலம் தேடு...",
  "Show Result": "முடிவை காட்டு",
  "Booking From date": "பதிவு செய்த தேதி முதல்",
  "Booking To date": "பதிவு செய்த தேதி வரை",
  "Dispatch From date": "அனுப்பி வைத்த தேதி முதல்",
  "Dispatch To date": "அனுப்பி வைத்த தேதி வரை",
  "Booking Details": "ஆர்டர் விவரங்கள்",
  "No orders found.": "ஆர்டர்கள் எதுவும் இல்லை.",
  "No matching orders.": "பொருந்தும் ஆர்டர்கள் இல்லை.",
  "Dispatch": "அனுப்பு",
  "Dispatching…": "அனுப்பப்படுகிறது…",
  "Move to Pending": "நிலுவைக்கு மாற்று",
  "Print": "பிரிண்ட்",
  "Printing…": "பிரிண்ட் ஆகிறது…",
  "If download didn't start, tap here and long‑press to save.": "டவுன்லோட் துவங்கவில்லை என்றால், இங்கே தட்டி நீண்ட நேரம் அழுத்தி சேமிக்கவும்.",
  "Account": "கணக்கு",
  "Syncing...": "புதுப்பிக்கப்படுகிறது...",
  "Not synced yet": "இன்னும் புதுப்பிக்கப்படவில்லை",
  "Product Code Settings": "புராடக்ட் கோட் செட்டிங்ஸ்",
  "Preview": "முன்னோட்டம்",
  "Text Placement": "உரை இடம்",
  "Text Color": "உரை நிறம்",
  "Saved!": "சேமிக்கப்பட்டது!",
  "Sales Reports": "விற்பனை அறிக்கைகள்",
  "Select Report Period": "அறிக்கை காலத்தைத் தேர்ந்தெடுக்கவும்",
  "From Date": "முதல் தேதி",
  "Dispatched Orders": "அனுப்பப்பட்ட ஆர்டர்கள்",
  "Total Sarees (from qty)": "மொத்த சேலைகள் (அளவிலிருந்து)",
  "Sales increased": "விற்பனை உயர்ந்தது",
  "Sales decreased": "விற்பனை குறைந்தது",
  "Download PDF Report (Auditor / IT Filing)": "PDF அறிக்கையை பதிவிறக்கு (ஆடிட்டர் / IT Filing)",
  "PDF includes summary, comparison with previous period, and detailed order table. Suitable for auditors and tax filing.": "PDF-ல் சுருக்கம், முந்தைய கால ஒப்பீடு, மற்றும் விரிவான ஆர்டர் அட்டவணை இருக்கும். ஆடிட்டர் மற்றும் வரி தாக்கலுக்கு பொருத்தமானது.",
  "Dispatched orders only, by dispatch date. View analytics and download PDF for auditors or IT filing.": "அனுப்பப்பட்ட ஆர்டர்கள் மட்டும், அனுப்பிய தேதிப்படி. பகுப்பாய்வு பார்க்கவும் மற்றும் ஆடிட்டர்/IT தாக்கலுக்காக PDF பதிவிறக்கவும்.",
  "Non-image files were skipped.": "படம் அல்லாத கோப்புகள் தவிர்க்கப்பட்டன",
  "Delete this batch?": "இந்த பேட்சை நீக்கவா?",
  "No saved images for this batch.": "இந்த பேட்சிற்கு சேமித்த படங்கள் இல்லை.",
  "Could not save images.": "படங்களை சேமிக்க முடியவில்லை.",
  "No batches in this period. Try another date range.": "இந்த காலப்பகுதியில் பேட்ச்கள் இல்லை. வேறு தேதியை முயற்சிக்கவும்.",
  "No photos selected": "புகைப்படங்கள் எதுவும் தேர்ந்தெடுக்கப்படவில்லை",
  "photo selected": "புகைப்படங்கள் தேர்ந்தெடுக்கப்பட்டது",
  "Pending": "நிலுவை",
  "Dispatched": "அனுப்பப்பட்டது",
  "Total Orders": "டோட்டல் ஆர்டர்ஸ்",
  "Own": "நமது",
  "No change from the previous period.": "பழைய காலத்தில் இருந்து எந்த மாற்றமும் இல்லை",
  "Failed to load data": "டேட்டா லோட் ஆகவில்லை",
  "Admin": "அட்மின்",
  "Workers": "வேலை செய்பவர்கள்",
  "No workers yet.": "வேலை செய்பவர்கள் யாரும் இல்லை",
  "No workers yet": "வேலை செய்பவர்கள் யாரும் இல்லை",
  "PDF Settings": "PDF செட்டிங்ஸ்",
  "Printer Setup": "பிரிண்டர் செட்டப்",
  "Content Type": "கன்டென்ட் டைப்",
  "Text size": "டெக்ஸ்ட் சைஸ்",
  "Logo Zoom": "லோகோ ஜூம்",
  "Y Position": "Y பொசிஷன்",
  "Live Preview": "லைவ் பிரிவியூ",
  "Sample Image": "சாம்பிள் இமேஜ்",
  "Manual Add (fallback)": "மேனுவல் ஆட் (ஃபால்பேக்)",
  "Top Right": "மேல் வலது",
  "Top Left": "மேல் இடது",
  "Bottom Left": "கீழ் இடது",
  "Bottom Right": "கீழ் வலது",
  "Red": "சிவப்பு",
  "White": "வெள்ளை",
  "Black": "கருப்பு",
  "Green": "பச்சை",
  "Blue": "நீலம்",
  "Yellow": "மஞ்சள்",
  "Default": "இயல்புநிலை",
  "Login": "லாகின்",
  "REGISTER": "பதிவு செய்",
  "Create your account": "உங்கள் கணக்கை உருவாக்கவும்",
  "Password reset successfully. Sign in with your new password.": "கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது. புதிய கடவுச்சொல்லால் உள்நுழைக.",
  "This account is already signed in on the maximum number of devices.": "இந்த கணக்கு ஏற்கனவே அதிகபட்ச சாதனங்களில் உள்நுழைந்துள்ளது.",
  "Need another device? Contact us on WhatsApp.": "மற்றொரு சாதனம் வேண்டுமா? வாட்ஸ்அப் மூலம் எங்களை தொடர்பு கொள்ளவும்.",
  "Email": "மின்னஞ்சல்",
  "Password": "கடவுச்சொல்",
  "Forgot Password?": "கடவுச்சொல் மறந்துவிட்டதா?",
  "Signing in…": "உள்நுழைகிறது…",
  "Don't have an account?": "கணக்கு இல்லையா?",
  "Register": "பதிவு செய்",
  "Already have an account?": "ஏற்கனவே கணக்கு உள்ளதா?",
  "Mobile Number": "அலைபேசி எண்",
  "Creating account…": "கணக்கு உருவாக்கப்படுகிறது…",
  "Open Gmail": "Gmail திறக்கவும்",
  "This email is already registered.": "இந்த மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.",
  "Forgot password": "கடவுச்சொல் மறந்துவிட்டதா",
  "Forgot Password": "கடவுச்சொல் மறந்துவிட்டதா",
  "Failed to send reset email": "ரீசெட் மின்னஞ்சலை அனுப்ப முடியவில்லை",
  "Enter your email to receive a reset link.": "ரீசெட் லிங்க் பெற உங்கள் மின்னஞ்சலை உள்ளிடவும்.",
  "Check your email for the reset link.": "ரீசெட் லிங்கிற்காக உங்கள் மின்னஞ்சலை சரிபார்க்கவும்.",
  "Sending…": "அனுப்பப்படுகிறது…",
  "Send Reset Link": "ரீசெட் லிங்க் அனுப்பு",
  "Back to Login": "லாகினுக்கு திரும்பு",
  "Invalid or expired reset link. Request a new one.": "ரீசெட் லிங்க் தவறானது அல்லது காலாவதியானது. புதியதை கோரவும்.",
  "Password updated. Redirecting to login…": "கடவுச்சொல் புதுப்பிக்கப்பட்டது. லாகினுக்கு மாற்றப்படுகிறது…",
  "Set new password": "புதிய கடவுச்சொல் அமைக்கவும்",
  "Set New Password": "புதிய கடவுச்சொல் அமைக்கவும்",
  "Enter your new password below.": "புதிய கடவுச்சொல்லை கீழே உள்ளிடவும்.",
  "New password": "புதிய கடவுச்சொல்",
  "Confirm password": "கடவுச்சொல்லை உறுதிப்படுத்து",
  "At least 6 characters": "குறைந்தது 6 எழுத்துகள்",
  "Confirm new password": "புதிய கடவுச்சொல்லை உறுதிப்படுத்து",
  "Update password": "கடவுச்சொல்லை புதுப்பி",
  "Reset Password": "கடவுச்சொல் மீட்டமை",
  "Password must be at least 6 characters.": "கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.",
  "Passwords do not match.": "கடவுச்சொற்கள் பொருந்தவில்லை.",
  "Failed to update password. The link may have expired.": "கடவுச்சொல்லை புதுப்பிக்க முடியவில்லை. லிங்க் காலாவதியாகி இருக்கலாம்.",
  "Password Changed!": "கடவுச்சொல் மாற்றப்பட்டது!",
  "Your password has been updated. Sign in with your new password.": "உங்கள் கடவுச்சொல் புதுப்பிக்கப்பட்டது. புதிய கடவுச்சொல்லால் உள்நுழைக.",
  "Open App": "ஆப்பை திறக்கவும்",
  "Show password": "கடவுச்சொல்லை காட்டு",
  "Hide password": "கடவுச்சொல்லை மறை",
};

const LanguageContext = createContext<LanguageContextValue>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>("en");

  useEffect(() => {
    if (typeof window === "undefined") return;
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved === "en" || saved === "ta") {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, lang);
    }
  };

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (key: string) => (language === "ta" ? (TA[key] ?? key) : key),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  return useContext(LanguageContext);
}

